// Copyright (C) 2025-2026 356C LLC
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#include <string>

/**
 * @file prerendered_images.h
 * @brief Helpers for selecting pre-rendered LVGL binary images
 *
 * Pre-rendered images are PNG files converted to LVGL's .bin format at specific
 * sizes. This eliminates runtime PNG decoding and scaling, dramatically improving
 * display performance on embedded devices.
 *
 * Image sizes are generated at build time by:
 *   - make gen-images         (splash screen)
 *   - make gen-printer-images (printer images)
 *
 * ## Splash Screen Sizes
 * - tiny:   240px (480x320 displays)
 * - small:  400px (800x480 displays, AD5M)
 * - medium: 614px (1024x600 displays)
 * - large:  768px (1280x720 displays)
 *
 * ## Printer Image Sizes
 * - 300px: For medium-large displays (800x480+)
 * - 150px: For small displays (480x320)
 *
 * @see scripts/regen_images.sh
 * @see scripts/regen_printer_images.sh
 */

namespace helix {

/**
 * @brief Get path to pre-rendered splash screen logo
 *
 * Selects the appropriate pre-rendered size based on screen width.
 * Falls back to original PNG if pre-rendered version doesn't exist.
 *
 * @param screen_width Display width in pixels
 * @return LVGL path (A:...) to the image, or empty string if none found
 */
[[nodiscard]] std::string get_prerendered_splash_path(int screen_width);

/**
 * @brief Get size category name for a screen width
 *
 * Maps screen width to size category:
 *   - < 600:  "tiny"   (480x320 class)
 *   - < 900:  "small"  (800x480 class, AD5M)
 *   - < 1100: "medium" (1024x600 class)
 *   - >= 1100: "large" (1280x720+ class)
 *
 * @param screen_width Display width in pixels
 * @return Size category name ("tiny", "small", "medium", "large")
 */
[[nodiscard]] const char* get_splash_size_name(int screen_width);

/**
 * @brief Get path to pre-rendered printer image
 *
 * Selects the appropriate pre-rendered size based on screen width.
 * Falls back to original PNG if pre-rendered version doesn't exist.
 *
 * @param printer_name Printer name (e.g., "creality-k1", "voron-v2")
 * @param screen_width Display width in pixels (used to pick 300px vs 150px)
 * @return LVGL path (A:...) to the image
 */
[[nodiscard]] std::string get_prerendered_printer_path(const std::string& printer_name,
                                                       int screen_width);

/**
 * @brief Get optimal printer image size for a screen width
 *
 * Returns the target size in pixels:
 *   - screen_width >= 600: 300px (medium-large displays)
 *   - screen_width < 600:  150px (small displays)
 *
 * @param screen_width Display width in pixels
 * @return Target size in pixels (300 or 150)
 */
[[nodiscard]] int get_printer_image_size(int screen_width);

/**
 * @brief Get size category name for 3D splash images
 *
 * Like get_splash_size_name() but uses both width and height to distinguish
 * K1 (480x400, "tiny_alt") from generic tiny (480x320, "tiny").
 *
 * @param screen_width Display width in pixels
 * @param screen_height Display height in pixels
 * @return Size category name ("tiny", "tiny_alt", "small", "medium", "large")
 */
[[nodiscard]] const char* get_splash_3d_size_name(int screen_width, int screen_height);

/**
 * @brief Get the target height of a pre-rendered 3D splash size category
 *
 * Returns the known screen height for a pre-rendered splash size name.
 * Used to validate that a pre-rendered image won't exceed the actual screen height.
 * Returns 0 for unknown sizes (caller should fall back to runtime scaling).
 *
 * @param size_name Size category name from get_splash_3d_size_name()
 * @return Target height in pixels, or 0 if unknown
 */
[[nodiscard]] int get_splash_3d_target_height(const char* size_name);

/**
 * @brief Get path to pre-rendered full-screen 3D splash image
 *
 * Returns the path to a composited full-screen splash image (logo centered
 * on a background-colored canvas at the exact screen resolution). These are
 * generated by `make gen-splash-3d` from the 3D logo variants.
 *
 * Falls back to the standard splash logo if the 3D variant doesn't exist.
 *
 * @param screen_width Display width in pixels
 * @param screen_height Display height in pixels
 * @param dark_mode true for dark variant, false for light
 * @return LVGL path (A:...) to the image, or empty string if none found
 */
[[nodiscard]] std::string get_prerendered_splash_3d_path(int screen_width, int screen_height,
                                                         bool dark_mode);

/**
 * @brief Check if a pre-rendered image exists
 *
 * @param path Filesystem path (without A: prefix)
 * @return true if file exists and is readable
 */
[[nodiscard]] bool prerendered_exists(const std::string& path);

// =========================================================================
// Persistent printer image cache (exact widget dimensions)
// =========================================================================

/**
 * @brief Get the directory for cached printer images at exact widget sizes
 *
 * Returns a dedicated cache directory (e.g., ~/.cache/helix/printer_images/).
 * Creates the directory if it doesn't exist.
 *
 * @return Filesystem path to the cache directory (no trailing slash)
 */
[[nodiscard]] std::string get_printer_image_cache_dir();

/**
 * @brief Get the cache file path for a printer image at exact dimensions
 *
 * @param source_image_path The resolved source image path (LVGL path with A: prefix)
 * @param width Exact widget width in pixels
 * @param height Exact widget height in pixels
 * @return Filesystem path to the cache .bin file
 */
[[nodiscard]] std::string get_cached_printer_image_path(const std::string& source_image_path,
                                                        int width, int height);

/**
 * @brief Generate a cached printer image at exact dimensions
 *
 * Loads the source image, resizes to exact width x height, converts to LVGL
 * ARGB8888 binary format, and writes atomically to the cache path.
 *
 * @param source_image_path The resolved source image path (LVGL path with A: prefix)
 * @param width Target width in pixels
 * @param height Target height in pixels
 * @param output_path Filesystem path for the output .bin file
 * @return true on success
 */
bool generate_cached_printer_image(const std::string& source_image_path, int width, int height,
                                   const std::string& output_path);

/**
 * @brief Prune old cached printer images
 *
 * If the cache directory has more than max_files entries, deletes the oldest
 * by modification time until max_keep remain.
 *
 * @param max_files Trigger pruning when file count exceeds this (default: 10)
 * @param max_keep Keep this many files after pruning (default: 5)
 */
void prune_printer_image_cache(int max_files = 10, int max_keep = 5);

/**
 * @brief Invalidate cached printer images whose filename starts with a given prefix
 *
 * Removes all dimension-specific cache files in the printer image cache directory
 * that match the source image basename. For example, if source_image_path is
 * "A:config/custom_images/my-printer-300.bin", this removes files like
 * "my-printer-300-480x320.bin" from the cache directory.
 *
 * @param source_image_path The LVGL source path (with or without A: prefix)
 * @return Number of cache files removed
 */
int invalidate_printer_image_cache(const std::string& source_image_path);

} // namespace helix
